language: python
python:
- '3.7'
script:
- python -m pytest --log-cli-level=INFO tests
- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
  user: __token__
  password:
    secure: FzsJRlaeOPr7xVaZfd8zmTefImVxzKwB1cuB80qeEgLNhtEWNkqKPo2LzpdU8iTNOAZY6nY2bNoHRk3kbXrdewI0mHIGMI9YLjy4giSiqR3BpozXIFwfs72W4YeKg/PS48RSCA6VCRCC/8m4hnzw8x+r3IEDkzbKGm1kqWk6CXBY7wcUU/fK7pQWv1lc76lTWo7FY14ChQ3Zmz9KzGqI+3Zea4jV3x6HH3EOKrsysrrkxKSJcwM80IXAhdCLbPyTierIYkePeZQfE29FYPThnY8NNNF7F6752x5hsJlXFRPxarygrSy7d16ueNBQI4vCjdRyw/pygyhc52tpAKeWAmz1v5MidP1/jxj5P/U+GMB8omqnrqaqOYbRcp2gT4w6Gyv6QGRav9NSmaJh59TyV/PVQ6Sw91zedXHSJ+2EHVg398F9aaQIeiamESnHI2lf16FHgAAhkCx455Rzqcc3uJGnyDAvWhoMVo3EUeu/ZEJrgsCAtc9lD5ovSNY3BAuUY9cTplQRij1gdykRiRL9JGUwzgDS1p4YMqSAK2AMoMg8iyds8/DC1uMFaUrIziHcgaV3FcCz8xKzCldRq44JDT/ZFVaeCwLz/M3NpR4Vc2M/jDaa+5P4yE9Y8sTyMETBCTvmtMEvalJ96A9stpsWLjDuIaTEfXU5iCsQOrlF7Kk=
